### ISSUE TITLE
RoadMap ?

### ISSUE THREAD

**Issue by giviz** [mofr/Diablerie#98]
Do you have a road map describing how you plan to move forward implementing the rest of the game ?

Even something basic that describe the majors steps.

**Comment by mofr** [comment]
Not a ROADmap, but a map of functionality to be implemented:
![image](https://user-images.githubusercontent.com/1718475/72953885-2c596b80-3dc9-11ea-94e6-a2ec8ee648b7.png)

**Comment by liberodark** [comment]
great :D

**Comment by giviz** [comment]
Awesome thank you.

I have to say, I'm really impressed by the amount of work and the quality of the code you have produced so far. I've learned a ton reading your code, and it's really easy to navigate through it :)

I'm making a Diablo 2 clone game (meaning 80% of D2 game mechanics, but with new art resources, so not using the original files), and I'm migrating from an other game engine to Unity, using Diablerie as a starting base, so thank you so much !

I've noticed that you make the ControlPanel different from the original one, is that something temporary and you plan to build as close as possible to the original game, or do you plan to adapt things along the way ?

I think that would be nice to have a few discussion oriented issues, for example one for the lighting and an other for the level generation for the wilderness, so we can gather information inside them. Do you mind if I create them ?

**Comment by mofr** [comment]
@giviz That is very valuable feedback, thank you! Could you share a link to your project, by the way?

Regarding ControlPanel and other differences - I don't want to stick to the original by all possible means. Some things are going to be rearranged a bit (a bit because I really like the original game). For example, original stamina mechanics don't make sense to me.

I won't mind if you create some space for information gathering for sure! Probably wiki is a better place. Also, consider joining the [Diablerie Discord](https://discord.gg/fDfm59u).
